export const POPPER_ROOT_ID = 'Echo-Extension-Tooltip-root'
export const POPPER_ID = 'Echo-Extension-Tooltip'
export const TOOLTIP_TEXT_CLASS = 'Echo-Extension-Tooltip-text'
export const ICON_CLASS1 = 'Echo-Extension-Bookmark-Button'
export const ICON_CLASS2 = 'Echo-Extension-Tooltip-bookmark'
export const TOOLTIP_ROOT_CLASS = 'Echo-Extension-Tooltip-root'
